default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fiscalfocus_development

 
  username: fiscalfocus
  password:  <%= ENV['FISCALFOCUS_DATABASE_PASSWORD'] %>

  host: localhost
  port: 5432

  
test:
  <<: *default
  database: fiscalfocus_test


production:
  <<: *default
  database: fiscalfocus_production
  username: fiscalfocus
  password: <%= ENV["FISCALFOCUS_DATABASE_PASSWORD"] %>